[project]
name = "take-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "selenium>=4.32.0",
]
